[phases.setup]
nixPkgs = ["python313Full", "nodejs_20"]

[phases.install]
cmds = [
  "python3.13 -m venv /app/.venv",
  "/app/.venv/bin/pip install -r requirements.txt",
  "cd frontend && npm install"
]

[phases.build]
cmds = [
  "cd frontend && npm run build"
]

[start]
cmd = "/app/.venv/bin/python main.py"
